name: Build and Push Docker Image (Multi-Platform)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag_suffix: amd64
          - platform: linux/arm64
            tag_suffix: arm64
          - platform: linux/arm/v7
            tag_suffix: armv7

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/hodladi/hodladiwallet/hodlwallet:${{ matrix.tag_suffix }}
            ghcr.io/hodladi/hodladiwallet/hodlwallet:${{ matrix.tag_suffix }}-latest
          platforms: ${{ matrix.platform }}
